FROM earthzetaorgorg/earthzetaorg:develop

# Install dependencies
COPY requirements-dev.txt /earthzetaorg/
RUN pip install numpy --no-cache-dir \
  && pip install -r requirements-dev.txt --no-cache-dir

# Empty the ENTRYPOINT to allow all commands
ENTRYPOINT []
